services:
  - type: web
    name: reciprocity
    runtime: node
    plan: free
    buildCommand: cd client && npm install --include=dev && npm run build
    startCommand: cd server && node index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
